name: Deploy Pages

on:
  repository_dispatch:
    types: [deploy-pages]

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: web-build
        path: build/web

    - uses: actions/upload-pages-artifact@v3
      with:
        path: build/web

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
